package org.symphonyoss.symphony.messageml.bi;

public enum BiFields {

  FORM("Form", BiEventType.MESSAGEML_ELEMENT_SENT),
  BUTTON("Button", BiEventType.MESSAGEML_ELEMENT_SENT),
  TEXT_AREA("TextArea", BiEventType.MESSAGEML_ELEMENT_SENT),
  TEXT_FIELD("TextField", BiEventType.MESSAGEML_ELEMENT_SENT),
  CHECKBOX("CheckBox", BiEventType.MESSAGEML_ELEMENT_SENT),
  RADIO("Radio", BiEventType.MESSAGEML_ELEMENT_SENT),
  TIME_PICKER("TimePicker", BiEventType.MESSAGEML_ELEMENT_SENT),
  TIMEZONE_PICKER("TimeZonePicker", BiEventType.MESSAGEML_ELEMENT_SENT),
  DATE_SELECTOR("DateSelector", BiEventType.MESSAGEML_ELEMENT_SENT),
  PERSON_SELECTOR("PersonSelector", BiEventType.MESSAGEML_ELEMENT_SENT),
  SELECT("Dropdown Menu", BiEventType.MESSAGEML_ELEMENT_SENT),
  OPTION("Option", BiEventType.MESSAGEML_ELEMENT_SENT),
  CHIME("Chimes", BiEventType.MESSAGEML_MESSAGE_SENT),
  CODE("Codes", BiEventType.MESSAGEML_MESSAGE_SENT),
  DIV("Divs", BiEventType.MESSAGEML_MESSAGE_SENT),
  ENTITY("Entity", BiEventType.MESSAGEML_ELEMENT_SENT),
  ENTITIES("Entities", BiEventType.MESSAGEML_MESSAGE_SENT),
  LINK("Links", BiEventType.MESSAGEML_MESSAGE_SENT),
  PARAGRAPH("Paragraphs", BiEventType.MESSAGEML_MESSAGE_SENT),
  PREFORMATTED("Pres", BiEventType.MESSAGEML_MESSAGE_SENT),
  SPAN("Spans", BiEventType.MESSAGEML_MESSAGE_SENT),
  TABLE("Tables", BiEventType.MESSAGEML_MESSAGE_SENT),
  TABLE_ROW_MAX("TableRowsMax", BiEventType.MESSAGEML_MESSAGE_SENT),
  TABLE_COLUMN_MAX("TableColumnsMax", BiEventType.MESSAGEML_MESSAGE_SENT),
  TABLE_CELL_COL_SPAN("TableCellsColSpan", BiEventType.MESSAGEML_MESSAGE_SENT),
  TABLE_CELL_ROW_SPAN("TableCellsRowSpan", BiEventType.MESSAGEML_MESSAGE_SENT),
  TABLE_HEADER("TableHeaders", BiEventType.MESSAGEML_MESSAGE_SENT),
  TABLE_FOOTER("TableFooters", BiEventType.MESSAGEML_MESSAGE_SENT),
  EMOJIS("Emojis", BiEventType.MESSAGEML_MESSAGE_SENT),
  MENTIONS("Mentions", BiEventType.MESSAGEML_MESSAGE_SENT),
  HASHTAGS("Hashtags", BiEventType.MESSAGEML_MESSAGE_SENT),
  CASHTAGS("Cashtags", BiEventType.MESSAGEML_MESSAGE_SENT),
  BULLET_LIST("Lists", BiEventType.MESSAGEML_MESSAGE_SENT),
  CARD("Cards", BiEventType.MESSAGEML_MESSAGE_SENT),
  EXPANDABLE_CARDS("ExpandableCards", BiEventType.MESSAGEML_MESSAGE_SENT),
  EXPANDABLE_CARDS_COLLAPSED("ExpandableCardsCollapsed", BiEventType.MESSAGEML_MESSAGE_SENT),
  EXPANDABLE_CARDS_CROPPED("ExpandableCardsCropped", BiEventType.MESSAGEML_MESSAGE_SENT),
  EXPANDABLE_CARDS_EXPANDED("ExpandableCardsExpanded", BiEventType.MESSAGEML_MESSAGE_SENT),
  HEADER("Headers", BiEventType.MESSAGEML_MESSAGE_SENT),
  IMAGE("Images", BiEventType.MESSAGEML_MESSAGE_SENT),
  IMAGE_DATA("ImagesData", BiEventType.MESSAGEML_MESSAGE_SENT),
  IMAGE_URL("ImagesUrl", BiEventType.MESSAGEML_MESSAGE_SENT),
  LINE_BREAK("LineBreaks", BiEventType.MESSAGEML_MESSAGE_SENT),
  INPUT_STEP("Input_Step", BiEventType.MESSAGEML_ELEMENT_SENT),
  TITLE("Title", BiEventType.MESSAGEML_ELEMENT_SENT),
  DEFAULT("Default", BiEventType.MESSAGEML_ELEMENT_SENT),
  PLACEHOLDER("Placeholder", BiEventType.MESSAGEML_ELEMENT_SENT),
  STYLE_COLOR("StyleColor", BiEventType.MESSAGEML_ELEMENT_SENT),
  STYLES_CUSTOM("StylesCustom", BiEventType.MESSAGEML_MESSAGE_SENT),
  STYLES_CLASS_TEMPO("StylesClassTempo", BiEventType.MESSAGEML_MESSAGE_SENT),
  STYLES_CLASS_OTHER("StylesClassOther", BiEventType.MESSAGEML_MESSAGE_SENT),
  TYPE("Type", BiEventType.MESSAGEML_ELEMENT_SENT),
  TYPE_MASKED_TRUE("Masked", BiEventType.MESSAGEML_ELEMENT_SENT),
  TYPE_MASKED_FALSE("Normal", BiEventType.MESSAGEML_ELEMENT_SENT),
  ENTITY_TYPE("EntityType", BiEventType.MESSAGEML_ELEMENT_SENT),
  LABEL("Label", BiEventType.MESSAGEML_ELEMENT_SENT),
  OPTIONS_COUNT("OptionsCount", BiEventType.MESSAGEML_ELEMENT_SENT),
  VALIDATION("Validation", BiEventType.MESSAGEML_ELEMENT_SENT),
  VALIDATION_MAX("Validation_Max", BiEventType.MESSAGEML_ELEMENT_SENT),
  VALIDATION_MIN("Validation_Min", BiEventType.MESSAGEML_ELEMENT_SENT),
  VALIDATION_PATTERN("Validation_Pattern", BiEventType.MESSAGEML_ELEMENT_SENT),
  VALIDATION_OPTIONS("Validation_Options", BiEventType.MESSAGEML_ELEMENT_SENT),
  HIGHLIGHTED_OPTIONS("HighlightedOptions", BiEventType.MESSAGEML_ELEMENT_SENT),
  VALIDATION_STRICT("Validation_Strict", BiEventType.MESSAGEML_ELEMENT_SENT),
  REQUIRED("Required", BiEventType.MESSAGEML_ELEMENT_SENT),
  MESSAGE_LENGTH("MessageLength", BiEventType.MESSAGEML_MESSAGE_SENT),
  ENTITY_JSON_SIZE("EntitiesJSONSize", BiEventType.MESSAGEML_MESSAGE_SENT),
  FREEMARKER("UseFreeMarker", BiEventType.MESSAGEML_ELEMENT_SENT),
  COUNT("Count", null);

  private final String value;
  private final BiEventType type;

  BiFields(String value, BiEventType type) {
    this.value = value;
    this.type = type;
  }

  public String getValue() {
    return value;
  }

  public BiEventType getType() {
    return type;
  }
}
