name: Build

on:
  push:
    branches: [ 'main', '*-rc' ]
  pull_request:
    branches: [ 'main', '*-rc' ]

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
    - name: Cache Maven packages
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up JDK
      uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3
      with:
        # 11 runtime needed for Sonar, we still build with 8 as a target
        distribution: 'adopt'
        java-version: 11
    - name: Build with Maven
      run: ./mvnw -B --file pom.xml verify
