name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: "Release"

    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Cache Maven packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          # 11 runtime needed for Sonar, we still build with 8 as a target
          distribution: 'temurin'
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase-env-var: MAVEN_GPG_PASSPHRASE
      - name: Set version from release tag
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          VERSION="${TAG_NAME#messageml-}"
          VERSION="${VERSION#v}"
          ./mvnw -B versions:set -DnewVersion="$VERSION" -DgenerateBackupPoms=false
      - name: Deploy on Maven Central
        run: ./mvnw -B deploy -Prelease -DskipTests
